user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Formato de log estándar de NGINX
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    # Formato extendido para EHUkene: incluye tiempo de respuesta y API Key.
    log_format  ehukene_fmt  '$remote_addr - $time_iso8601 '
                             '"$request" $status $body_bytes_sent '
                             'rt=$request_time '
                             'apikey="$http_x_api_key"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    # Configuración de sites activos
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;
}
